<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:html="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta content="text/html; charset=utf-8" />

    <link rel="stylesheet" type="text/css" media="all" href="http://www.gnome.org/wp-content/themes/gnome-grass/style.css"></link>
    <link rel="stylesheet" type="text/css" media="all" href="http://www.gnome.org/wp-content/themes/gnome-grass/css/reset.css"></link>
    <link rel="stylesheet" type="text/css" media="all" href="http://www.gnome.org/wp-content/themes/gnome-grass/css/text.css"></link>
    <link rel="stylesheet" type="text/css" media="all" href="http://www.gnome.org/wp-content/themes/gnome-grass/css/960.css"></link>
    <link rel="stylesheet" type="text/css" media="all" href="http://developer.gnome.org/skin/lgo2010.css"></link>

    <title>{TITLE}</title>

    <link href="{HOME_HREF}" rel="home" title="{HOME_DESC}"></link>
    <link href="{UP_HREF}" rel="up" title="{UP_DESC}"></link>
    <link href="{PREV_HREF}" rel="prev" title="{PREV_DESC}"></link>
    <link href="{NEXT_HREF}" rel="next" title="{NEXT_DESC}"></link>
  </head>
  <body>
    <div id="container" class="gtk-doc">
      <div class="content">
        <table id="top" width="100%" cellpadding="2" summary="Navigation header" cellspacing="2" class="navigation">
          <tbody>
            <tr valign="middle">
              <td>
                <a accesskey="p" href="{PREV_HREF}">
                  <img width="24" alt="Prev" src="http://developer.gnome.org/gtk3/stable/left.png" border="0" height="24"></img>
                </a>
              </td>
              <td></td>
              <td>
                <a accesskey="h" href="index.html">
                  <img width="24" alt="Home" src="http://developer.gnome.org/gtk3/stable/home.png" border="0" height="24"></img>
                </a>
              </td>
              <th width="100%" align="center">{TITLE}</th>
              <td>
                <a accesskey="n" href="{NEXT_HREF}">
                  <img width="24" alt="Next" src="http://developer.gnome.org/gtk3/stable/right.png" border="0" height="24"></img>
                </a>
              </td>
            </tr>
          </tbody>
        </table>

        <div class="part">
          <div class="partintro">
            {CONTENT}
          </div>
          <div class="footer">
            <hr />
            Generated by <a href="{PHD_URL}">PhD</a> {PHD_VERSION}
          </div>
        </div><!--end part-->
      </div><!--end content-->
      
      <div id="footer_art" class="default"></div>
    </div><!--end container-->

    <div class="clearfix"></div>
    <div id="footer_grass"></div>
    <div id="footer"></div>
  </body>
</html>
